apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vkgrag.fullname" . }}-env
  labels:
    {{- include "vkgrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "vkgrag.envContent" . | nindent 4 }}
